[package]
name = "lang"
edition = "2021"
version = "0.1.0"
build = "build.rs"
author = ["João Silveira <joao.freixial.silveira@gmail.com>"]

[dependencies]
regex = "1.7.1"
lalrpop-util = "0.19.8"

[build-dependencies]
lalrpop = "0.19.8"