/// The AST module contains the AST types.
/// The AST is generated by the parser.

/// The `expr` module contains the AST types for expressions.
mod expression;

/// The `statement` module contains the AST types for statements.
mod statement;

/// The `program` module contains the AST types for the program.
mod program;