/// The `lexer` module contains the lexer for the language.
/// The lexer is hand-written.
pub mod lexer;

/// The `ast` module contains the abstract syntax tree for the language.
/// The AST is generated by the parser.
pub mod ast;

/// The `display` module contains the logic for displaying human-readable
/// messages to the user.
pub mod display;
