/// The `lexer` module contains the lexer for the language.
/// The lexer is hand-written.
pub mod lexer;

/// The `ast` module contains the abstract syntax tree for the language.
/// The AST is generated by the parser.
pub mod ast;

/// The `location` module contains the `Location` struct.
/// The `Location` struct is used to track the location of tokens. 
/// It is used to provide better error messages.
pub mod location;